#!/usr/bin/env python3
"""Code generated by ChatGPT.

Parse swissprot flat files and get info on ec-code and subcellular location
"""

import gzip
import re
from pathlib import Path

import polars as pl
from tqdm import tqdm

# Full EC numbers like 1.2.3.4
EC_RE = re.compile(r"EC=([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)")

# Start of the specific CC topic
SCL_START = "CC   -!- SUBCELLULAR LOCATION:"
CC_PREFIX = "CC       "  # continuation lines often begin like this


def normalize_scl_text(text: str) -> list[str]:
    """Heuristic extraction of subcellular location terms from UniProt comment text.

    Input is the concatenated SUBCELLULAR LOCATION block text.
    We split on '.' and ';' and keep plausible location phrases.
    This won't be perfect (UniProt is rich text), but works well for joins/filtering.
    """
    # remove evidence braces like {ECO:...} and trailing notes
    text = re.sub(r"\{ECO:[^}]+\}", "", text)
    text = text.replace("SUBCELLULAR LOCATION:", "").strip()

    # unify whitespace
    text = re.sub(r"\s+", " ", text)

    # split on '.' first (often separates sentences)
    chunks = []
    for sent in text.split("."):
        sent = sent.strip()
        if not sent:
            continue
        # further split on ';' (often separates locations)
        for part in sent.split(";"):
            p = part.strip()
            if p:
                chunks.append(p)

    # clean common prefixes
    cleaned = []
    for c in chunks:
        # drop leading qualifiers that aren't locations
        c = re.sub(r"^(Note=|Isoform .*?:)\s*", "", c).strip()
        # trim parenthetical notes
        c = re.sub(r"\s*\(.*?\)\s*$", "", c).strip()
        if c:
            cleaned.append(c)

    # de-duplicate while preserving order
    seen = set()
    out = []
    for c in cleaned:
        if c not in seen:
            seen.add(c)
            out.append(c)
    return out


def build_ec_scl_mapping(
    dat_gz: str, out_parquet: str, batch_size: int = 250_000
):
    """Stream-parse UniProt .dat.gz and write a Parquet mapping:
      accession -> [ECs], [subcellular_location_terms]
    Only emits entries that have >=1 EC.
    """
    rows_acc = []
    rows_ec = []
    rows_scl = []

    def flush(df_idx: int):
        if not rows_acc:
            return
        df = pl.DataFrame(
            {
                "target": rows_acc,
                "ec-code": rows_ec,
                "location": rows_scl,
            },
        )
        # Write partitioned shards for easier incremental handling
        shard = Path(out_parquet)
        shard = shard.with_suffix("")  # remove .parquet if present
        shard.parent.mkdir(parents=True, exist_ok=True)
        shard_path = shard.parent / f"{shard.name}.part{df_idx:04d}.parquet"
        df.write_parquet(shard_path, compression="zstd")

        rows_acc.clear()
        rows_ec.clear()
        rows_scl.clear()

    entry_acs = set()
    entry_ecs = set()
    scl_lines = []
    in_entry = False
    in_scl = False
    part = 0

    def end_entry():
        nonlocal part, in_scl
        # Only keep entries with EC annotation (as you requested)
        if entry_ecs and entry_acs:
            ecs_sorted = sorted(entry_ecs)
            scl_terms = (
                normalize_scl_text(" ".join(scl_lines)) if scl_lines else []
            )
            for acc in entry_acs:
                rows_acc.append(acc)
                rows_ec.append(ecs_sorted)
                rows_scl.append(scl_terms)

            if len(rows_acc) >= batch_size:
                flush(part)
                part += 1

        entry_acs.clear()
        entry_ecs.clear()
        scl_lines.clear()
        in_scl = False

    with gzip.open(dat_gz, "rt", encoding="utf-8", errors="replace") as fh:
        for line in tqdm(fh):
            if line.startswith("ID   "):
                in_entry = True
                continue

            if not in_entry:
                continue

            if line.startswith("AC   "):
                parts = line[5:].strip().split(";")
                for p in parts:
                    a = p.strip()
                    if a:
                        entry_acs.add(a)
                continue

            if line.startswith("DE   ") and "EC=" in line:
                for ec in EC_RE.findall(line):
                    entry_ecs.add(ec)
                continue

            # Capture subcellular location block.
            # This is in CC lines and may span multiple lines until next "-!-" topic or end of entry.
            if line.startswith(SCL_START):
                in_scl = True
                scl_lines.append(line.replace("CC   ", "").strip())
                continue

            if in_scl:
                if line.startswith("CC   -!- ") and not line.startswith(
                    SCL_START
                ):
                    # new CC topic begins
                    in_scl = False
                elif line.startswith("CC   ----") or (
                    line.startswith("CC   -!- ") is False
                    and not line.startswith("CC")
                ):
                    # defensive: unexpected structure
                    in_scl = False
                # continuation CC lines often start with "CC       "
                elif line.startswith("CC"):
                    scl_lines.append(line.replace("CC   ", "").strip())
                # keep going; don't "continue" because we may have turned off in_scl
                # but that's fine
            if line.startswith("//"):
                end_entry()
                in_entry = False

    # flush remainder
    flush(part)


def combine_parts_to_single(out_prefix: str, final_parquet: str):
    """Optional: combine shard parts into a single Parquet file (still columnar).
    Polars can also scan multiple part files directly.
    """
    prefix = Path(out_prefix).with_suffix("")
    parts = sorted(prefix.parent.glob(f"{prefix.name}.part*.parquet"))
    df = pl.concat([pl.read_parquet(p) for p in parts], how="vertical_relaxed")
    df.write_parquet(final_parquet, compression="zstd")


if __name__ == "__main__":
    # Example usage:
    # python build_map.py uniprot_sprot.dat.gz uniprot_ec_scl_map.parquet
    import sys

    if len(sys.argv) != 3:
        print(
            "Usage: python build_map.py <uniprot_sprot.dat.gz> <out_prefix.parquet>",
            file=sys.stderr,
        )
        raise SystemExit(2)
    build_ec_scl_mapping(sys.argv[1], sys.argv[2])
    print("Done.")
